-- Using the NYC Taxi public dataset (Yellow Trips) from Google BigQuery, complete the following exercises:


-- Exercise 1: Count the number of trips in January 2021
SELECT COUNT(*) FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021` where data_file_month="1" LIMIT 1000 

-- Exercise 2: Calculate the total revenue generated by taxi trips in 2021
SELECT 
  SUM(total_amount) - SUM(airport_fee) - SUM(mta_tax)-SUM(imp_surcharge) AS calculated_amount
FROM 
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`;
  
-- Exercise 3: Find the most popular pickup location
SELECT 
  MAX(pickup_location_id) AS most_popular
FROM 
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021` order by most_popular;

-- Exercise 4: Analyze the number of trips per hour of the day
SELECT 
  EXTRACT(HOUR FROM pickup_datetime) AS pickup_hour,
  COUNT(pickup_location_id) AS trip_count
FROM 
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`
GROUP BY 
  pickup_hour
ORDER BY 
  pickup_hour;


-- Exercise 5: Calculate the average trip distance
SELECT 
  avg(trip_distance)
FROM 
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`;

-- Exercise 6: Find the longest trip by distance
SELECT 
  pickup_location_id, trip_distance
FROM 
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021` order by trip_distance desc;


-- Exercise 7: Calculate the total number of passengers by payment type
SELECT 
  COUNT(passenger_count), payment_type
FROM 
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021` group by payment_type;


-- Exercise 8: Find the most common drop-off location for trips paid by credit card
SELECT 
  COUNT(dropoff_location_id) AS trip_count, 
  payment_type
FROM 
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`
WHERE 
  payment_type = '1'
GROUP BY 
  payment_type;


-- Exercise 9: Calculate the total number of trips that had more than 4 passengers
SELECT 
  COUNT(pickup_location_id)
FROM 
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`
WHERE 
  passenger_count>4
GROUP BY 
  passenger_count;

-- Exercise 10: Subquery - Find the average fare for trips longer than the average trip distance
SELECT 
  AVG(fare_amount) AS average_fare
FROM 
  `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`
WHERE 
  trip_distance > (SELECT AVG(trip_distance) FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2021`);
